# GitHub Action for Laravel
name: Testing Laravel
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.3

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
 
    - name: Install composer dependencies
      run: |
        composer install --no-scripts

    - name: Make sqlite file
      run: touch database/database.sqlite

    - name: Prepare Laravel Application
      run: |
        cp .env.example .env
        php artisan key:generate
        composer dumpautoload
        php artisan optimize
 
    - name: Run Testsuite
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
        DB_HOST:
        DB_PORT:
        DB_USERNAME:
        DB_PASSWORD:
        DB_CHARSET:
        DB_COLLATION:
      run: vendor/bin/phpunit tests/